# Start from the pytorch official image (ubuntu-22.04 + cuda-12.6 + python-3.11)
# https://hub.docker.com/r/pytorch/pytorch/tags
FROM pytorch/pytorch:2.8.0-cuda12.9-cudnn9-devel
# docker build -t empasy/pytorch:th2.8.0-cu129-flashattn2.8.3-cxx11abi0-devel -f Dockerfile.base .

# Define environments
ENV MAX_JOBS=16
ENV VLLM_WORKER_MULTIPROC_METHOD=spawn
ENV DEBIAN_FRONTEND=noninteractive
ENV NODE_OPTIONS=""
ENV PIP_ROOT_USER_ACTION=ignore

# Define installation arguments
ARG APT_SOURCE=https://mirrors.tuna.tsinghua.edu.cn/ubuntu/
ARG PIP_INDEX=https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple

# Set apt source
RUN cp /etc/apt/sources.list /etc/apt/sources.list.bak && \
    { \
    echo "deb ${APT_SOURCE} jammy main restricted universe multiverse"; \
    echo "deb ${APT_SOURCE} jammy-updates main restricted universe multiverse"; \
    echo "deb ${APT_SOURCE} jammy-backports main restricted universe multiverse"; \
    echo "deb ${APT_SOURCE} jammy-security main restricted universe multiverse"; \
    } > /etc/apt/sources.list

# Install systemctl and wget
RUN apt-get update && \
    apt-get install -y -o Dpkg::Options::="--force-confdef" systemd wget && \
    apt-get clean

# Install git and vim
RUN apt-get update && \
    apt-get install -y git vim && \
    apt-get clean

# Install gcc and g++
RUN apt-get update && \
    apt-get install -y gcc g++ && \
    apt-get clean

# Change pip source
RUN pip config set global.index-url "${PIP_INDEX}" && \
    pip config set global.extra-index-url "${PIP_INDEX}" && \
    pip install --no-cache-dir --upgrade pip packaging wheel setuptools

# Install flash-attn-2.8.0.post2 (cxx11abi=False)
RUN pip install flash-attn

# Install flashinfer-0.3.1
RUN pip install flashinfer-python

# Reset pip config
RUN pip config unset global.index-url && \
    pip config unset global.extra-index-url
